# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0008_auto_20180328_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseentitlement',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='courseentitlementsupportdetail',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_details', to='entitlements.CourseEntitlement'),
        ),
    ]
